### ISSUE TITLE
すしが正常に表示されない

### ISSUE THREAD

**Issue by JAJP** [mzyy94/like2sushi#14]
タイムライン等で正常に表示されなくなりました。。。
![(´・ω・｀)](https://cloud.githubusercontent.com/assets/15177572/11181910/d01e56a2-8ca9-11e5-935f-ab365389d183.png)

**Comment by petamoriken** [comment]
そのバグについては #11 で修正されています。
再ダウンロードしていただくと正常に表示されると思います🍣🍣🍣

**Comment by mzyy94** [comment]
確認おくれてすいません🍣
#11にて修正されているので、新しいバージョンをダウンロードするなりgit pullするなりして修正版を適用してみてください。
もしそれでも治らなかった場合、このIssueを再Openしてご報告いただけると幸いです。
